export enum MessageType {
  PING = "PING",
  PONG = "PONG",

  PAIRING_HELLO = "PAIRING_HELLO",
  PAIRING_SESSION_CREATE = "PAIRING_SESSION_CREATE",
  PAIRING_SESSION_CREATED = "PAIRING_SESSION_CREATED",
  PAIRING_JOIN = "PAIRING_JOIN",
  PAIRING_JOINED = "PAIRING_JOINED",
  PAIRING_CONFIRM = "PAIRING_CONFIRM",
  PAIRING_COMPLETE = "PAIRING_COMPLETE",
  PAIRING_EXPIRED = "PAIRING_EXPIRED",

  TRUSTED_DEVICE_HELLO = "TRUSTED_DEVICE_HELLO",
  TRUSTED_DEVICE_ONLINE = "TRUSTED_DEVICE_ONLINE",
  TRUSTED_DEVICE_OFFLINE = "TRUSTED_DEVICE_OFFLINE",
  TRUSTED_DEVICE_STATUS = "TRUSTED_DEVICE_STATUS",

  DEVICE_STATUS = "DEVICE_STATUS",

  TEXT_SHARE = "TEXT_SHARE",
  TEXT_SHARE_ACK = "TEXT_SHARE_ACK",
  TEXT_SHARE_ERROR = "TEXT_SHARE_ERROR",

  FILE_OFFER = "FILE_OFFER",
  FILE_ACCEPT = "FILE_ACCEPT",
  FILE_REJECT = "FILE_REJECT",
  FILE_CHUNK = "FILE_CHUNK",
  FILE_PROGRESS = "FILE_PROGRESS",
  FILE_COMPLETE = "FILE_COMPLETE",
  FILE_CANCEL = "FILE_CANCEL",

  NOTIFICATION_POSTED = "NOTIFICATION_POSTED",
  NOTIFICATION_REMOVED = "NOTIFICATION_REMOVED",
  NOTIFICATION_DISMISS = "NOTIFICATION_DISMISS",
  NOTIFICATION_DISMISS_RESULT = "NOTIFICATION_DISMISS_RESULT",
  NOTIFICATION_REPLY = "NOTIFICATION_REPLY",
  NOTIFICATION_REPLY_RESULT = "NOTIFICATION_REPLY_RESULT",
  LAN_DISCOVERY_PROBE = "LAN_DISCOVERY_PROBE",

  ERROR = "ERROR"
}

